# to use: 
# `conda env update --file env.yaml`
name: arabic_nlp
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - dvc
  - numpy=1.21.5
  - seaborn
  - scikit-learn=1.0.2
  - pandas=1.4.2
  - pyarrow
  - pip
  - matplotlib=3.5.1
  - regex = 2022.3.15
  - scipy=1.8.0
  - gensim
  - spacy
  - python-flair
  - Glob2
  - arabic_reshaper
  - python-bidi
  - nltk
  - snowballstemmer
  - pip:
    - datatest
    - coconut-develop[kernel]
    - bertopic
    - ar_wordcloud
 